// Platzhalter-Stellen, solange die zvoove-Zugangsdaten fehlen.
//
// Diese Datei wird NICHT mehr verwendet, sobald ZVOOVE_API_BASE und
// ZVOOVE_API_KEY in der Umgebung gesetzt sind (siehe lib/zvoove.js). Sie hat
// exakt die Struktur, die der Adapter aus der API erzeugt, damit sich beim
// Umschalten an den Seiten nichts ändert.
//
// Inhalte orientieren sich an den echten Stellen auf flixwork.de (Stand
// 31.08.2026), damit Layout, Textlängen und Filter realistisch wirken.

const BENEFITS_STANDARD = [
  "Übertarifliche Bezahlung nach GVP-Tarif plus Branchenzuschläge",
  "Unbefristeter Arbeitsvertrag mit realer Übernahmechance",
  "Urlaubs- und Weihnachtsgeld",
  "Persönlicher Ansprechpartner, der Sie beim Namen kennt",
  "Kostenfreie Arbeitskleidung und Schutzausrüstung",
];

const BENEFITS_FACH = [
  "Übertarifliche Bezahlung plus Branchenzuschläge",
  "Unbefristeter Arbeitsvertrag mit realer Übernahmechance",
  "Weiterbildungen und Scheinverlängerungen auf unsere Kosten",
  "Urlaubs- und Weihnachtsgeld",
  "Persönlicher Ansprechpartner, der Sie beim Namen kennt",
];

export const demoJobs = [
  {
    id: "demo-001",
    slug: "fachkraft-lagerlogistik-m-w-d-bis-20-eur-std-34212-melsungen",
    titel: "Fachkraft Lagerlogistik (m/w/d)",
    kategorie: "logistik-fachkraefte",
    ort: "Melsungen",
    plz: "34212",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Schichtbetrieb, 35 bis 40 Stunden",
    lohnVon: 17,
    lohnBis: 20,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Für einen Medizintechnik-Standort in Melsungen suchen wir eine Fachkraft für Lagerlogistik im Zweischichtbetrieb.",
    aufgaben: [
      "Wareneingang prüfen, buchen und einlagern",
      "Kommissionieren mit Scanner und MDE-Gerät",
      "Bedienen von Front- und Schubmaststapler",
      "Bestandspflege und Inventurunterstützung",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Fachkraft für Lagerlogistik oder vergleichbare Erfahrung",
      "Gültiger Staplerschein",
      "Bereitschaft zur Zweischicht",
      "Sorgfalt und Zuverlässigkeit",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-25",
  },
  {
    id: "demo-002",
    slug: "helfer-versand-m-w-d-200-startpraemie-34117-kassel-hessen",
    titel: "Helfer Versand (m/w/d)",
    kategorie: "logistik-hilfskraefte",
    ort: "Kassel",
    plz: "34117",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Frühschicht, Montag bis Freitag",
    lohnVon: 14.5,
    lohnBis: 16,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Einstieg ohne Vorkenntnisse: Versandvorbereitung bei einem Kasseler Handelsunternehmen, geregelte Frühschicht.",
    aufgaben: [
      "Waren für den Versand vorbereiten und verpacken",
      "Versandetiketten anbringen und Sendungen dokumentieren",
      "Paletten zusammenstellen und sichern",
      "Ordnung und Sauberkeit im Versandbereich",
    ],
    profil: [
      "Keine Vorkenntnisse nötig, wir arbeiten Sie ein",
      "Deutsch in Grundzügen",
      "Zuverlässigkeit und Teamgeist",
      "Bereitschaft zur Frühschicht",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-28",
  },
  {
    id: "demo-003",
    slug: "instandhalter-elektrotechnik-m-w-d-bis-25-eur-std-34117-kassel",
    titel: "Instandhalter Elektrotechnik (m/w/d)",
    kategorie: "industrie-fachkraefte",
    ort: "Kassel",
    plz: "34117",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Dreischicht mit Schichtzulagen",
    lohnVon: 21,
    lohnBis: 25,
    praemie: 300,
    startdatum: "ab sofort",
    kurztext:
      "Anspruchsvolle Instandhaltung in einem Produktionsbetrieb mit hohem Automatisierungsgrad, Übernahme ausdrücklich gewünscht.",
    aufgaben: [
      "Störungssuche und Instandsetzung an Produktionsanlagen",
      "Wartung nach Instandhaltungsplan",
      "Umbauten und Optimierungen an Steuerungen",
      "Dokumentation der Arbeiten im System",
    ],
    profil: [
      "Ausbildung als Elektroniker für Betriebstechnik oder Mechatroniker",
      "Erfahrung in der industriellen Instandhaltung",
      "Grundkenntnisse SPS von Vorteil",
      "Bereitschaft zur Schichtarbeit",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-20",
  },
  {
    id: "demo-004",
    slug: "kommissionierer-pick-by-voice-m-w-d-200-startpraemie-34117-kassel",
    titel: "Kommissionierer Pick-by-Voice (m/w/d)",
    kategorie: "logistik-hilfskraefte",
    ort: "Kassel",
    plz: "34117",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Wechselschicht Früh und Spät",
    lohnVon: 15,
    lohnBis: 17,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Kommissionierung per Sprachsteuerung in einem modernen Lager, Einarbeitung durch das Kundenteam.",
    aufgaben: [
      "Kommissionieren der Aufträge per Pick-by-Voice",
      "Zusammenstellen und Sichern der Paletten",
      "Kontrolle der Warenqualität",
      "Rückmeldung von Fehlmengen",
    ],
    profil: [
      "Erste Lagererfahrung von Vorteil, aber kein Muss",
      "Deutsch für die Sprachsteuerung",
      "Bereitschaft zur Wechselschicht",
      "Körperliche Belastbarkeit",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-27",
  },
  {
    id: "demo-005",
    slug: "lagerhelfer-m-w-d-200-eur-startpraemie-34474-diemelstadt",
    titel: "Lagerhelfer (m/w/d)",
    kategorie: "logistik-hilfskraefte",
    ort: "Diemelstadt",
    plz: "34474",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Tagschicht, Montag bis Freitag",
    lohnVon: 14.5,
    lohnBis: 15.5,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Allgemeine Lagertätigkeiten bei einem Produktionsbetrieb in Diemelstadt, langfristiger Einsatz.",
    aufgaben: [
      "Be- und Entladen von Lkw",
      "Ein- und Auslagern von Fertigware",
      "Etikettieren und Verpacken",
      "Unterstützung bei der Inventur",
    ],
    profil: [
      "Keine Vorkenntnisse nötig",
      "Zuverlässigkeit und Pünktlichkeit",
      "Staplerschein von Vorteil",
      "Eigener Pkw wegen der Lage sinnvoll",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-24",
  },
  {
    id: "demo-006",
    slug: "reifenverlader-m-w-d-bis-18-eur-std-34497-korbach",
    titel: "Reifenverlader (m/w/d)",
    kategorie: "logistik-hilfskraefte",
    ort: "Korbach",
    plz: "34497",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Dreischicht mit Zulagen",
    lohnVon: 16,
    lohnBis: 18,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Körperlich fordernder Einsatz mit sehr guter Bezahlung bei einem Reifenhersteller in Korbach.",
    aufgaben: [
      "Verladen von Reifen auf Lkw und Container",
      "Sortieren nach Größen und Aufträgen",
      "Sichtkontrolle der Ware",
      "Sauberhalten des Verladebereichs",
    ],
    profil: [
      "Körperliche Belastbarkeit",
      "Bereitschaft zur Dreischicht",
      "Zuverlässigkeit",
      "Erste Lagererfahrung wünschenswert",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-19",
  },
  {
    id: "demo-007",
    slug: "staplerfahrer-m-w-d-bis-18-eur-std-34225-baunatal",
    titel: "Staplerfahrer (m/w/d)",
    kategorie: "logistik-fachkraefte",
    ort: "Baunatal",
    plz: "34225",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Wechselschicht",
    lohnVon: 16.5,
    lohnBis: 18,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Staplereinsatz in der Automobilzulieferung in Baunatal, moderner Fuhrpark und feste Teams.",
    aufgaben: [
      "Transport von Material zwischen Lager und Produktion",
      "Ein- und Auslagern mit Schubmaststapler",
      "Buchungen im Warenwirtschaftssystem",
      "Sichtprüfung der Ladungssicherung",
    ],
    profil: [
      "Gültiger Staplerschein und Fahrpraxis",
      "Erfahrung mit Schubmaststapler von Vorteil",
      "Bereitschaft zur Wechselschicht",
      "Sorgfältige Arbeitsweise",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-26",
  },
  {
    id: "demo-008",
    slug: "produktionshelfer-m-w-d-200-startpraemie-37073-goettingen",
    titel: "Produktionshelfer (m/w/d)",
    kategorie: "industrie-hilfskraefte",
    ort: "Göttingen",
    plz: "37073",
    region: "Niedersachsen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Zweischicht",
    lohnVon: 14.5,
    lohnBis: 16.5,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Sauberer Produktionseinsatz in Göttingen mit strukturierter Einarbeitung und guter Übernahmequote.",
    aufgaben: [
      "Bestücken und Bedienen von Produktionsanlagen",
      "Sicht- und Qualitätskontrolle",
      "Verpacken der Fertigware",
      "Dokumentation der Produktionsdaten",
    ],
    profil: [
      "Keine Vorkenntnisse nötig",
      "Sorgfalt und Konzentration",
      "Bereitschaft zur Zweischicht",
      "Deutsch in Grundzügen",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-29",
  },
  {
    id: "demo-009",
    slug: "maschinenbediener-m-w-d-bis-19-eur-std-04808-wurzen",
    titel: "Maschinenbediener (m/w/d)",
    kategorie: "industrie-fachkraefte",
    ort: "Wurzen",
    plz: "04808",
    region: "Sachsen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Dreischicht",
    lohnVon: 16,
    lohnBis: 19,
    praemie: 300,
    startdatum: "ab sofort",
    kurztext:
      "Selbstständiges Fahren von Produktionsanlagen bei einem Lebensmittelhersteller in Wurzen.",
    aufgaben: [
      "Rüsten, Anfahren und Überwachen der Anlagen",
      "Störungen beheben und melden",
      "Qualitätsprüfungen nach Vorgabe",
      "Führen der Schichtdokumentation",
    ],
    profil: [
      "Technische Ausbildung oder Erfahrung als Maschinenbediener",
      "Technisches Verständnis",
      "Bereitschaft zur Dreischicht",
      "Selbstständige Arbeitsweise",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-21",
  },
  {
    id: "demo-010",
    slug: "kommissionierer-m-w-d-200-startpraemie-04109-leipzig",
    titel: "Kommissionierer (m/w/d)",
    kategorie: "logistik-hilfskraefte",
    ort: "Leipzig",
    plz: "04109",
    region: "Sachsen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Wechselschicht",
    lohnVon: 14.5,
    lohnBis: 16,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Kommissionierung in einem großen Distributionszentrum im Leipziger Norden, gut mit den Öffentlichen erreichbar.",
    aufgaben: [
      "Kommissionieren nach Pickliste und Scanner",
      "Verpacken und Etikettieren",
      "Bereitstellen der Ware für den Versand",
      "Mitwirken bei Bestandskontrollen",
    ],
    profil: [
      "Erste Lagererfahrung von Vorteil",
      "Bereitschaft zur Wechselschicht",
      "Sorgfalt und Tempo",
      "Deutsch in Grundzügen",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-30",
  },
  {
    id: "demo-011",
    slug: "elektroniker-betriebstechnik-m-w-d-bis-24-eur-std-06184-kabelsketal",
    titel: "Elektroniker Betriebstechnik (m/w/d)",
    kategorie: "handwerksberufe",
    ort: "Kabelsketal",
    plz: "06184",
    region: "Sachsen-Anhalt",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Tagschicht mit Rufbereitschaft",
    lohnVon: 20,
    lohnBis: 24,
    praemie: 300,
    startdatum: "ab sofort",
    kurztext:
      "Elektroinstallation und Anlagentechnik bei einem Logistikdienstleister nahe Halle, überwiegend Tagschicht.",
    aufgaben: [
      "Installation und Prüfung elektrischer Anlagen",
      "Fehlersuche an Förder- und Sortiertechnik",
      "Wartung nach Prüffristen",
      "Dokumentation nach DGUV V3",
    ],
    profil: [
      "Abgeschlossene Ausbildung im Elektrohandwerk",
      "Erfahrung mit Fördertechnik von Vorteil",
      "Führerschein Klasse B",
      "Selbstständige und saubere Arbeitsweise",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-18",
  },
  {
    id: "demo-012",
    slug: "anlagenmechaniker-shk-m-w-d-bis-25-eur-std-06108-halle",
    titel: "Anlagenmechaniker SHK (m/w/d)",
    kategorie: "handwerksberufe",
    ort: "Halle",
    plz: "06108",
    region: "Sachsen-Anhalt",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Tagschicht, Montag bis Freitag",
    lohnVon: 21,
    lohnBis: 25,
    praemie: 300,
    startdatum: "ab sofort",
    kurztext:
      "Montage und Wartung von Heizungs- und Sanitäranlagen im Raum Halle, Fahrzeug und Werkzeug stellen wir.",
    aufgaben: [
      "Montage von Heizungs-, Sanitär- und Lüftungsanlagen",
      "Rohrleitungsbau in Kupfer, Stahl und Kunststoff",
      "Inbetriebnahme und Wartung",
      "Kundendienst im Umkreis",
    ],
    profil: [
      "Ausbildung als Anlagenmechaniker SHK oder vergleichbar",
      "Berufserfahrung in Montage oder Kundendienst",
      "Führerschein Klasse B",
      "Freundliches Auftreten beim Kunden",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-22",
  },
  {
    id: "demo-013",
    slug: "sachbearbeiter-auftragsabwicklung-m-w-d-34117-kassel",
    titel: "Sachbearbeiter Auftragsabwicklung (m/w/d)",
    kategorie: "kaufmaennische-berufe",
    ort: "Kassel",
    plz: "34117",
    region: "Hessen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Gleitzeit, Montag bis Freitag",
    lohnVon: 17,
    lohnBis: 20,
    praemie: 200,
    startdatum: "ab sofort",
    kurztext:
      "Kaufmännischer Einsatz im Innendienst eines Kasseler Mittelständlers, moderne Büroräume und Gleitzeit.",
    aufgaben: [
      "Auftragserfassung und Auftragsverfolgung",
      "Korrespondenz mit Kunden und Lieferanten",
      "Erstellen von Lieferpapieren und Rechnungen",
      "Pflege der Stammdaten im ERP-System",
    ],
    profil: [
      "Kaufmännische Ausbildung",
      "Sicherer Umgang mit MS Office",
      "Erfahrung mit einem ERP-System von Vorteil",
      "Strukturierte Arbeitsweise",
    ],
    benefits: BENEFITS_STANDARD,
    aktualisiertAm: "2026-08-23",
  },
  {
    id: "demo-014",
    slug: "berufskraftfahrer-ce-m-w-d-bis-21-eur-std-34346-hann-muenden",
    titel: "Berufskraftfahrer CE (m/w/d)",
    kategorie: "sonstige-branchen",
    ort: "Hann. Münden",
    plz: "34346",
    region: "Niedersachsen",
    beschaeftigungsart: "Vollzeit",
    arbeitszeit: "Tagtouren, keine Fernfahrten",
    lohnVon: 18,
    lohnBis: 21,
    praemie: 300,
    startdatum: "ab sofort",
    kurztext:
      "Regionale Tagtouren ab Hann. Münden, abends zu Hause, moderner Fuhrpark.",
    aufgaben: [
      "Auslieferung im Nahverkehr",
      "Be- und Entladen der Fahrzeuge",
      "Ladungssicherung nach Vorschrift",
      "Führen der Fahrzeugdokumentation",
    ],
    profil: [
      "Führerschein CE mit Eintrag 95",
      "Fahrerkarte",
      "Erfahrung im Nahverkehr von Vorteil",
      "Freundliches Auftreten beim Kunden",
    ],
    benefits: BENEFITS_FACH,
    aktualisiertAm: "2026-08-29",
  },
];
